# Installs Ukernel libs
name: checkout-install-ukernels
description: Install Ukernel libs
inputs:
  lib_name:
    description: Name of the workflow to install wheels from
    default: None
outputs:
  path:
    description: Name of the workflow to install wheels from
    value: ${{ steps.xsmm.outputs.path || steps.onednn.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Checkout XsMM
      if: inputs.lib_name == 'XSMM'
      uses: actions/checkout@v4
      with:
        repository: libxsmm/libxsmm
        submodules: recursive
        ref: 63251ac815e88593d06f36b3e07180f117abae37
        path: libxsmm

    - name: Install XsMM
      if: inputs.lib_name == 'XSMM'
      id: xsmm
      shell: bash
      run: |
        set -e
        cd libxsmm
        BLAS=0 make PREFIX=../libxsmm-install install
        export XSMM_INSTALL=../libxsmm-install
        export XSMM_LIBRARY_DIRS=$XSMM_INSTALL/lib
        export XSMM_INCLUDE_DIRS=$XSMM_INSTALL/include
        cd ..
        if [[ -z "$( ls -A ${GITHUB_WORKSPACE}/libxsmm-install )" ]]; then
          echo "XSMM not installed properly"
          exit -1
        fi
        echo "path=${GITHUB_WORKSPACE}/libxsmm-install" >> $GITHUB_OUTPUT

    - name: Checkout OneDNN
      if: inputs.lib_name == 'OneDNN'
      uses: actions/checkout@v4
      with:
        repository: oneapi-src/oneDNN
        submodules: recursive
        ref: 1e3bc8d0b92e845a186bf0c23eccee187eb5eb81
        path: oneDNN

    - name: Install OneDNN
      if: inputs.lib_name == 'OneDNN'
      id: onednn
      shell: bash
      run: |
        set -e
        cd oneDNN
        mkdir -p build
        cd build
        cmake .. -DDNNL_EXPERIMENTAL_UKERNEL=ON -DCMAKE_BUILD_TYPE=Release
        make -j
        make DESTDIR=../install_dir install
        cd ../..
        if [[ -z "$( ls -A ${GITHUB_WORKSPACE}/oneDNN/install_dir )" ]]; then
          echo "OneDNN not installed properly"
          exit -1
        fi
        echo "path=${GITHUB_WORKSPACE}/oneDNN/install_dir/usr/local" >> $GITHUB_OUTPUT
