"""Allowlist of test_core.py tests supported on the CPU backend.

test_core.py itself carries no CPU selection metadata (no `@pytest.mark.cpu`);
when TRITON_DEFAULT_BACKEND=cpu, the hook in python/test/conftest.py keeps only
the tests listed here and deselects everything else in test_core.py. This keeps
the shared test file identical to upstream while CPU coverage stays extensible:
to enable a newly supported test, just append its function name below.

Each entry is a plain test function name (no parametrization). The hook fails
the run if an entry matches nothing collected, so renames/removals upstream are
caught loudly instead of silently shrinking coverage.

Derived from the `@pytest.mark.cpu` set that #251 added (minus tests that no
longer exist upstream), see `git log` for the conversion commit.
"""

CPU_TEST_CORE_ALLOWLIST = frozenset([
    "test_abs",
    "test_abs_fp8",
    "test_addptr",
    "test_arange",
    "test_assume",
    "test_atomic_cas",
    "test_atomic_rmw",
    "test_atomic_rmw_predicate",
    "test_bfloat16_mul_rounds_to_nearest_even",
    "test_bin_op",
    "test_bin_op_constexpr",
    "test_bitwise_op",
    "test_broadcast",
    "test_call",
    "test_cast",
    "test_cat",
    "test_clamp",
    "test_clamp_symmetric",
    "test_compare_op",
    "test_const",
    "test_constexpr",
    "test_constexpr_if_return",
    "test_constexpr_scalar_shape",
    "test_constexpr_shape",
    "test_convert_float16_to_float32",
    "test_default",
    "test_dot",
    "test_dot3d",
    "test_dot_max_num_imprecise_acc",
    "test_dot_mulbroadcasted",
    "test_dot_without_load",
    "test_dtype_codegen",
    "test_enable_fp_fusion",
    "test_expand_dims",
    "test_expand_dims_error_cases",
    "test_floordiv",
    "test_for_iv",
    "test_full",
    "test_generic_reduction",
    "test_histogram",
    "test_if",
    "test_if_call",
    "test_if_else",
    "test_if_return",
    "test_index1d",
    "test_int1_bin_op_wraparound",
    "test_interleave_scalars",
    "test_invalid_pid_axis",
    "test_invalid_slice",
    "test_join",
    "test_join_scalars",
    "test_join_with_mma",
    "test_load_cache_modifier",
    "test_load_scalar_with_mask",
    "test_load_store_same_ptr",
    "test_masked_load",
    "test_masked_load_scalar",
    "test_masked_load_shared_memory",
    "test_math_divide_op",
    "test_math_erf_op",
    "test_math_fma_op",
    "test_math_member_fn",
    "test_math_member_fn_rejects_fp16",
    "test_math_op",
    "test_max_returns_zero",
    "test_nested_if_else_return",
    "test_noinline",
    "test_num_programs",
    "test_num_threads",
    "test_optimize_thread_locality",
    "test_permute",
    "test_precise_math",
    "test_propagate_nan",
    "test_ptx_cast",
    "test_reduce",
    "test_reduce1d",
    "test_reshape",
    "test_reshape_err",
    "test_scan2d",
    "test_shapes_as_params",
    "test_shift_op",
    "test_slice",
    "test_split",
    "test_split_to_scalar",
    "test_static_range",
    "test_store_cache_modifier",
    "test_store_constant",
    "test_store_eviction_policy",
    "test_temp_var_in_loop",
    "test_tensor_atomic_add_non_exclusive_offset",
    "test_tensor_atomic_cas",
    "test_tensor_atomic_rmw",
    "test_tl_range_num_stages",
    "test_trans_2d",
    "test_trans_4d",
    "test_transpose",
    "test_umulhi",
    "test_unary_op",
    "test_unsigned_name_mangling",
    "test_value_specialization",
    "test_value_specialization_overflow",
    "test_vectorization",
    "test_vectorization_hints",
    "test_where",
    "test_where_broadcast",
    "test_while",
    "test_while_condition",
])
