name: Build and test (using a local LLVM build)
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      # You can name your branch dev-foo to get CI runs.
      - 'dev-**'
  push:
    branches:
      - main

env:
  python-verson: '3.11'

jobs:
  build-with-local-llvm-and-optional-deps:
    name: Build with local LLVM and optional dependencies on GNR Intel x86(fp16, bf16, amx)
    runs-on:
      - granite-rapids
      - intel
      - x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python ${{ env.python-verson }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-verson }}

      - name: Install UV
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld g++ zlib1g-dev cmake ninja-build wget

      - name: Build and test with scripts from XSMM repository
        run: |
          wget https://github.com/libxsmm/triton-cpu/raw/refs/heads/xsmm-main/upstream-proj-build.sh
          wget https://github.com/libxsmm/triton-cpu/raw/refs/heads/xsmm-main/upstream-proj-setup.sh
          wget https://github.com/libxsmm/triton-cpu/raw/refs/heads/xsmm-main/upstream-proj-test.sh
          bash upstream-proj-build.sh
          source upstream-proj-setup.sh
          bash upstream-proj-test.sh
          python python/tutorials/cpu-sfc-matmul.py --bench -M 512 1024 2048 -N 512 1024 2048 -K 512 1024 2048
